name: Documentation

on:
  push:
    branches: [main]
    paths: ['README.md', 'docs/**']
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build documentation
      run: |
        echo "📚 Building documentation..."
        mkdir -p ./docs-build
        # Copy README and any other docs
        cp README.md ./docs-build/
        cp LICENSE ./docs-build/ || true
        echo "Documentation built successfully"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-build
        publish_branch: gh-pages
